---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/pages
  label: Pages
  create: documents
  match: "**/*.md"
  new_doc_ext: md
upload_dir: uploads
public_path: "/src/uploads"
front_matter_path: "../uploads"
use_front_matter_path: false
file_template: "../uploads/:filename:"
